[package]
name = "hijri_calendar"
version = "0.1.0"
authors = ["Mukhamad Ikhsan <ikhsan@kodelokus.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
